# Generated by Django 5.2.8 on 2026-05-11 23:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/events_asset/default_img.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
