# Generated by Django 5.2.8 on 2026-05-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default_img.jpg', null=True, upload_to='events_asset'),
        ),
    ]
