# Generated by Django 5.2.8 on 2026-05-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='events_asset'),
        ),
    ]
